"""tambah admin

Revision ID: ac37a2b76855
Revises: 
Create Date: 2026-02-25 14:49:41.310552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac37a2b76855'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sso_email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sso_email'), ['sso_email'], unique=True)

    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_admin_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin')),
    sa.UniqueConstraint('user_id', name=op.f('uq_admin_user_id'))
    )
    op.create_table('lecturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('nip', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('profile_picture', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_lecturer_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lecturer')),
    sa.UniqueConstraint('nip', name=op.f('uq_lecturer_nip')),
    sa.UniqueConstraint('user_id', name=op.f('uq_lecturer_user_id'))
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nim', sa.String(length=20), nullable=False),
    sa.Column('profile_picture', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('research_title', sa.String(length=500), nullable=True),
    sa.Column('status_bimbingan', sa.String(length=100), nullable=True),
    sa.Column('masa', sa.String(length=20), nullable=True),
    sa.Column('program_studi', sa.String(length=100), nullable=True),
    sa.Column('ut_daerah', sa.String(length=100), nullable=True),
    sa.Column('current_progress_step', sa.Integer(), nullable=True),
    sa.Column('zoom_link', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_student_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student')),
    sa.UniqueConstraint('user_id', name=op.f('uq_student_user_id'))
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_nim'), ['nim'], unique=True)

    op.create_table('bimbingan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('proposed_date', sa.Date(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturer.id'], name=op.f('fk_bimbingan_lecturer_id_lecturer')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_bimbingan_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bimbingan'))
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('attachment_filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('fk_chat_message_sender_id_user')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_chat_message_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_timestamp'), ['timestamp'], unique=False)

    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('progress_step', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_document_student_id_student')),
    sa.ForeignKeyConstraint(['uploader_id'], ['user.id'], name=op.f('fk_document_uploader_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_table('honorarium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('activity', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('paid_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturer.id'], name=op.f('fk_honorarium_lecturer_id_lecturer')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_honorarium_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_honorarium'))
    )
    op.create_table('seminar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('seminar_type', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('final_grade', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_seminar_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seminar'))
    )
    op.create_table('supervision',
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturer.id'], name=op.f('fk_supervision_lecturer_id_lecturer')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_supervision_student_id_student')),
    sa.PrimaryKeyConstraint('lecturer_id', 'student_id', name=op.f('pk_supervision'))
    )
    op.create_table('supervisor_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('role_applied_for', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('request_date', sa.DateTime(), nullable=True),
    sa.Column('research_title_applied', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturer.id'], name=op.f('fk_supervisor_application_lecturer_id_lecturer')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_supervisor_application_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supervisor_application'))
    )
    op.create_table('document_approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('lecturer_id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('fk_document_approval_document_id_document')),
    sa.ForeignKeyConstraint(['lecturer_id'], ['lecturer.id'], name=op.f('fk_document_approval_lecturer_id_lecturer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_approval'))
    )
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seminar_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_date', sa.DateTime(), nullable=True),
    sa.Column('final_grade', sa.String(length=10), nullable=True),
    sa.Column('general_notes', sa.Text(), nullable=True),
    sa.Column('criteria_scores', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['evaluator_id'], ['lecturer.id'], name=op.f('fk_evaluation_evaluator_id_lecturer')),
    sa.ForeignKeyConstraint(['seminar_id'], ['seminar.id'], name=op.f('fk_evaluation_seminar_id_seminar')),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], name=op.f('fk_evaluation_student_id_student')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evaluation'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation')
    op.drop_table('document_approval')
    op.drop_table('supervisor_application')
    op.drop_table('supervision')
    op.drop_table('seminar')
    op.drop_table('honorarium')
    op.drop_table('document')
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_timestamp'))

    op.drop_table('chat_message')
    op.drop_table('bimbingan')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_nim'))

    op.drop_table('student')
    op.drop_table('lecturer')
    op.drop_table('admin')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sso_email'))

    op.drop_table('user')
    # ### end Alembic commands ###
